[METAL] Fix problem with convolution unrolling
I wasn't able to run inception-v2 model on iPad Air. Model was
successfully compiled but when I run the model, I got the following
error: `Compute function exceeds available temporary registers`

The problem occurs due to the generated kernel for one convolution was
more than 4000 lines long. It happened due to unrolling.

As a solution, decrease value of `auto_unroll_max_step`.