[Apps] Pin android_camera TensorFlow/Keras dependency version
At the moment, android camera is installing latest TF and Keras
which is causing the following issue in CI:

```
  File ".../keras/dtensor/lazy_variable.py", line 26, in <module>
    from tensorflow.python.trackable import base as trackable
ModuleNotFoundError: No module named 'tensorflow.python.trackable'
```

This patch fixes the versions in the last known working versions
of both: TF 2.9.1 and Keras 2.9.

Change-Id: I0a9e0272edf62b717b42b1a7c6157f3982e1a326