[CI] Upgrade sccache version to 0.7.* (#16366)
* [CI] Upgrade sccache version to 0.7.*

Sccache was previously pinned at version 0.3.3, however, there has
recently been an issue when installing some of its dependencies:

```
error[E0277]: expected a `Fn(reqwest::Request, &'a mut task_local_extensions::extensions::Extensions, reqwest_middleware::Next<'a>)` closure, found `RetryAfterMiddleware`
```

Upgrading the version of sccache to the latest seems to resolve this
error.

* Use an alternative mirror for boost artifacts

The JFrog artifactory link is down, so changing to an alternative
mirror mentioned in boostorg/boost#842.