[CI] Remove mps3_an547 from the CI
Remove for now the mps3_an547 board from the CI.

Both mps2_an512 and mps3_an547 boards hit a hard to debug issue when
tests run against them in the CI environment.

The failure seems not tied to any specific test and usually consists in
the board stopping to respond the host that will show a generic trace
due to a timeout when trying to call a function on the device, like:

tvm._ffi.base.TVMError: MicroSessionTimeoutError: failed to read reply message after timeout 10s

The issue is very hard to reproduce locally and its root cause can be
in one or more of the stack components being stressed, like the QEMU
emulation and its interaction with the particular CI environment,
Zephyr's serial driver (the boards share the same driver), microTVM code
using Zephyr's bufffer and serial APIs, and TVM RPC protocol over the
serial line when and with a serial FIFO too small (1 byte in the case of
booth board UARTs), or even a "hiccup" when running QEMU on the CI
inside a container.

Hence the most reasonable thing to do is to remove the boards from the
CI until that issue is solved.

This commit also removes the commented out lines for running the
mps2_an512 board in the CI so the script file don't get polluted. The
mps2_an512 is currently disabled.

Signed-off-by: Gustavo Romero <gustavo.romero@linaro.org>