[BYOC][NPU] Fix integration tests not running
As we were using `python` rather than `python3`, when ran in the docker containers it resulted in:
```
Exception: The minimal Python requirement is Python 3.6
```

This masked a further error of the wrong NPU configuration being used
for the tests.